services:
  external_nginx:
    image: nginx:stable-alpine
    container_name: external_nginx_img_server
    build:
      context: .
      args:
        - EXTERNAL_PORT = ${EXTERNAL_PORT}
        - INNER_PORT = ${INNER_PORT}
    ports:
      - ${EXTERNAL_PORT}:80
    volumes:
      - ./app:/var/www/images_server
      - ./config/nginx/external/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env

  inner_nginx:
    container_name: inner_nginx_img_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${INNER_PORT}:80
    volumes:
      - ./app:/var/www/images_server
      - ./config/nginx/inner/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    env_file:
      - ./.env
