services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_images_server
    ports:
      - ${PORT}:80
    volumes:
      - ./app:/var/www/images_server
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
